// transform registry into typescript declarations
import {
	readLatin1String, heap32VectorToArray, 
	typeIdToTypeName, typeNamesToParameters
} from './embind'
import { EmscriptenModule } from './emscripten';
import { HintFunction } from './hint';
import { Registry, FreeFunction, EnumInfo, EnumValueInfo, StringGetter } from './injection/registry';
import {
	getClassExternalDeclaration, getClassModuleDeclaration
} from './declaration/classes'


const getFunctionDeclaration = 
        (
            module: EmscriptenModule, registry: Registry, 
            hint: HintFunction
        ) => 
        (funcInfo: FreeFunction) => {
	const {name,argCount,rawArgTypesAddr} = funcInfo;
	// TODO
	const nameStr = readLatin1String(module)(name)
	const argTypes = heap32VectorToArray(module)(argCount, rawArgTypesAddr);
	const argTypeNames = argTypes.map(typeIdToTypeName(module,registry))
	const [returnType,...parameterTypes] = argTypeNames;
	const parameters = typeNamesToParameters(parameterTypes)
	const preComment = hint({name:nameStr}).comment
	return `${preComment}\n\t${nameStr}(${parameters}): ${returnType};`
}

// identical
const getEnumInterfaceDeclaration = 
		(module: EmscriptenModule, registry: Registry) => 
		(enumInfo: EnumInfo) => 
{
	const {getName,values} = enumInfo;
	const name = getName(module)
	return `\t${name}: ${name}Enum`
}

const getEnumValueDeclaration = 
		(
			module: EmscriptenModule, registry: Registry,
			enumName: string
		) => (valInfo: EnumValueInfo) => {
	const {name,enumValue} = valInfo;
	const humanName = readLatin1String(module)(name)
	return `\t${humanName}: ${enumName},`
}

const getEnumDeclaration = 
		(module: EmscriptenModule,registry: Registry) => 
		(enumInfo: EnumInfo) => 
{
	const {getName,values} = enumInfo;
	const name = getName(module)
	return [
		`declare const valid${name}: unique symbol;`,
		`export interface ${name} {[valid${name}]: true}`,
		`interface ${name}Enum {`,
		...enumInfo.values.map(
			getEnumValueDeclaration(module,registry,name)),
		'}'
	].join('\n')
}


// TS is not responsible for enforcing number sizes (int8 vs int32 etc)
const declarationForNumber = 
		(module: EmscriptenModule,registry: Registry) => 
		(name: StringGetter) => {
	return `type ${name(module)} = number;`
}

const indent = (text: string) => `\t${text}`

function getModuleDeclaration(
		module: EmscriptenModule,registry: Registry,hint: HintFunction
) {
	return [
		"export interface CustomEmbindModule {",
		...registry.functions
			.map(getFunctionDeclaration(module,registry,hint))
			.map(indent),
		...Object.values(registry.classes)
			.map(getClassModuleDeclaration(module,registry))
			.map(indent),
		...Object.values(registry.enums)
			.map(getEnumInterfaceDeclaration(module,registry)),
		"}",
		"declare function factory(): Promise<CustomEmbindModule>;",
		"export default factory;"
	].join('\n')
}

export function declarationsForRegistry(
	module: EmscriptenModule, registry: Registry,hint: HintFunction)
{
	return [
		[ '// generated by TSEMBIND ', '' ],
		[ '// define type aliases for various native number types' ],
		registry.numbers.map(declarationForNumber(module,registry)),
		[ '' ],
		Object.values(registry.classes)
			.map(getClassExternalDeclaration(module,registry)),
		Object.values(registry.enums)
			.map(getEnumDeclaration(module,registry)),
		[getModuleDeclaration(module,registry,hint)]
	].flat().join('\n')
}

module.exports = {declarationsForRegistry}
